spring:
  datasource:
    username: root
    password: qianlima
    url: jdbc:mysql://172.18.30.87:3306/gulimall_ums?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: gulimall-member
  cloud:
    nacos:
      discovery:
        server-addr: 172.18.30.87:8848
        #正式环境建议该属性打开
      config:
        import-check:
          enabled: false
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000
